### ISSUE TITLE
Homebridge Plugin

### ISSUE THREAD

**Issue by Slavitacus** [fredericvl/py-agua-iot#1]
Hello,
Are you working on a hombridge pluging aqua-iot?
Thanks

**Comment by fredericvl** [comment]
Hi @Slavitacus,

Currently I'm not planning on creating a homebridge plugin, sorry.
I will leave this request open in case of anyone (including myself) wants to pick this up later.

Grtz!

**Comment by securechicken** [comment]
Hi @Slavitacus, @fredericvl,
I am working on it actually, at least for a limited number of stove brands at first.
I wrote a previous plugin for an older Micronova module, and for a specific stove brand only, dealing with some quite heavy HomeKit/HomeBridge limitations (no devices types like heaters or stove exist in HomeKit) - but that worked anyway.

Older Micronova module is being discontinued by this brand, and replaced by a Micronova Agua IOT module. While considering writing a new Homebridge module based on Agua IOT, I found this repo - I would not have reverse engineered the whole API like I had to do for the older module and app, but with this repo at hand, and having discovered recently the Agua IOT API is even publicly documented... :)
I am currently testing a working private version, and will probably publish a public alpha in the coming week.

**Comment by Daavince** [comment]
Hi @securechicken,
I am running into issues connecting to the agua iot API to control my Piazzetta (I had to replace my old wifi module recently due to deprecation). I get passed the register app stage using the python module developed by @fredericvl. But get stuck at the login step (failed to authenticate message). Did you do anything special to make the homebridge plugin work with your Piazzetta module? It seems you got it working. I am looking to integrate this directly into Domoticz, as I run my home automation on that platform. 
Tx!
